# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 18:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')])),
                ('address', models.CharField(max_length=200)),
                ('credit_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checking_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saving_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('state', models.CharField(max_length=20)),
                ('sub_state', models.CharField(max_length=20)),
                ('request', models.CharField(max_length=20)),
                ('permission', models.IntegerField()),
                ('user_type', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')])),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('critical', models.IntegerField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_balance', models.CharField(max_length=20)),
                ('to_balance', models.CharField(max_length=20)),
                ('credit_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('request_id', models.IntegerField()),
            ],
        ),
    ]
