# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='mail_address',
            field=models.CharField(default=b'NOT_PROVIDED', max_length=1000),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=b'', max_length=128),
        ),
    ]
