# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='mail_address',
            field=models.CharField(default='NOT_PROVIDED', max_length=1000),
        ),
        migrations.AddField(
            model_name='individual',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128),
        ),
    ]
